"use client";

import { useState } from "react";
import { Camera, Check, CircleAlert, LoaderCircle, QrCode, ReceiptText, ScanLine, Wallet } from "lucide-react";
import { useDemo } from "@/components/demo-provider";
import { parseQrValue, qrValue, restaurantWallet } from "@/lib/demo";
import { DemoTag, Eyebrow, Notice } from "@/components/ui";

type Result = { kind: "valid" | "used" | "invalid"; message: string; voucherId?: string; restaurant?: string } | null;
export default function RestaurantPage() {
  const { state, dispatch } = useDemo(); const [input, setInput] = useState(""); const [result, setResult] = useState<Result>(null); const [pending, setPending] = useState(false);
  const validate = (raw = input) => { const secret = parseQrValue(raw); const voucher = state.vouchers.find((v) => v.qrSecret === secret); if (!voucher) return setResult({ kind: "invalid", message: "유효하지 않은 QR입니다. 문자열을 다시 확인해 주세요." }); if (voucher.status === "redeemed") return setResult({ kind: "used", message: "이미 사용 완료된 식사권입니다.", voucherId: voucher.id, restaurant: voucher.restaurant }); if (voucher.status !== "issued") return setResult({ kind: "invalid", message: "아직 발급되지 않은 식사권입니다." }); setResult({ kind: "valid", message: "사용 가능한 식사권입니다.", voucherId: voucher.id, restaurant: voucher.restaurant }); };
  const loadSample = () => { const voucher = state.vouchers.find((v) => v.status === "issued" && v.qrSecret); if (!voucher?.qrSecret) { setResult({ kind: "invalid", message: "먼저 복지기관 화면에서 QR을 발급해 주세요." }); return; } const value = qrValue(voucher.qrSecret); setInput(value); validate(value); };
  const redeem = async () => { if (!result?.voucherId) return; setPending(true); await new Promise((r) => setTimeout(r, 900)); dispatch({ type: "REDEEM", secret: parseQrValue(input) }); setPending(false); setResult({ ...result, kind: "used", message: "식사 제공과 가상 정산이 완료되었습니다." }); };
  const settlements = state.vouchers.filter((v) => v.status === "redeemed");
  return <section className="section page-section"><div className="shell"><div className="page-heading"><div><Eyebrow>제휴 식당 업무 화면</Eyebrow><h1>QR을 확인하고 식사를 제공해요</h1><p>지정된 일회용 식사권인지 확인한 뒤 완료 처리합니다.</p></div><div className="wallet-chip"><Wallet size={16} /><span>식당 지갑</span><strong>{restaurantWallet}</strong><DemoTag /></div></div>
  <div className="workspace-grid"><div className="scanner-card"><div className="scanner-visual"><ScanLine /><div><Camera /><span>카메라 QR 스캔</span><small>발표 환경에서는 아래 샘플 불러오기를 이용하세요.</small></div></div><button className="button secondary wide" onClick={loadSample}>발급된 QR 불러오기</button><div className="divider"><span>또는 QR 문자열 직접 입력</span></div><label className="sr-only" htmlFor="qr-input">QR 문자열</label><textarea id="qr-input" value={input} onChange={(e) => { setInput(e.target.value); setResult(null); }} placeholder="MEALLINK:GANAK:ML-..." /><button className="button dark wide" disabled={!input} onClick={() => validate()}>식사권 유효성 확인</button></div>
  <div className="validation-card">{!result ? <div className="empty-validation"><span><QrCode /></span><h2>식사권을 확인해 주세요</h2><p>QR을 불러오거나 문자열을 직접 입력하면 유효 여부를 보여드립니다.</p></div> : <div className={`result ${result.kind}`}><span>{result.kind === "valid" ? <Check /> : <CircleAlert />}</span><DemoTag>{result.kind === "valid" ? "검증 완료" : "사용 상태"}</DemoTag><h2>{result.message}</h2>{result.voucherId && <div className="receipt"><div><span>식사권 번호</span><strong>{result.voucherId}</strong></div><div><span>지정 식당</span><strong>{result.restaurant}</strong></div><div><span>정산 단위</span><strong>0.001 Sepolia ETH · 데모</strong></div></div>}{result.kind === "valid" && <button className="button wide" disabled={pending} onClick={redeem}>{pending ? <><LoaderCircle className="spin" /> 가상 정산 처리 중</> : <>식사 제공 완료 <Check /></>}</button>}{result.kind === "used" && result.message.includes("완료") && <Notice tone="success">후원자의 타임라인과 캠페인 통계가 자동으로 갱신되었습니다.</Notice>}</div>}</div></div>
  <div className="settlement-section"><div className="section-heading"><div><h2>최근 가상 정산 기록</h2><p>실제 자금 이동이 없는 시연 기록입니다.</p></div><DemoTag /></div>{settlements.length ? <div className="table-wrap"><table><thead><tr><th>식사권</th><th>식당</th><th>상태</th><th>테스트 금액</th></tr></thead><tbody>{settlements.map((v) => <tr key={v.id}><td>{v.id}</td><td>{v.restaurant}</td><td><span className="status-pill redeemed"><Check />정산 완료</span></td><td>0.001 Sepolia ETH</td></tr>)}</tbody></table></div> : <div className="mini-empty"><ReceiptText /> 아직 정산된 데모 식사권이 없습니다.</div>}</div></div></section>;
}
